CREATE DATABASE CONDORES
GO

USE CONDORES
GO

CREATE TABLE PROFESOR(
	IDPROFESOR INT PRIMARY KEY,
	NOMBRE VARCHAR(45) NOT NULL,
	ASIGNATURA VARCHAR(45) NOT NULL,
	CURSO VARCHAR(45) NOT NULL
)
GO

CREATE TABLE ALUMNO(
	IDALUMNO INT PRIMARY KEY,
	NOMBRE VARCHAR(45) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	APODERADO VARCHAR(45) NOT NULL,
	PROFESOR_IDPROFESOR INT NOT NULL
)
GO

ALTER TABLE ALUMNO ADD CONSTRAINT FK_PROF_ALUM
FOREIGN KEY (PROFESOR_IDPROFESOR) REFERENCES PROFESOR(IDPROFESOR);
GO
------------------------------------------------------------------

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY,
	USUARIO VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL
)
GO

INSERT INTO USUARIO VALUES(1,'JUAN','PASS1234')
INSERT INTO USUARIO VALUES(2,'ANA','PASS456')
GO
