//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CONDORESModel", "FK_PROF_ALUM", "PROFESOR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(capaDALC.PROFESOR), "ALUMNO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(capaDALC.ALUMNO), true)]

#endregion

namespace capaDALC
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CONDORESEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CONDORESEntities usando la cadena de conexión encontrada en la sección 'CONDORESEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public CONDORESEntities() : base("name=CONDORESEntities", "CONDORESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CONDORESEntities.
        /// </summary>
        public CONDORESEntities(string connectionString) : base(connectionString, "CONDORESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CONDORESEntities.
        /// </summary>
        public CONDORESEntities(EntityConnection connection) : base(connection, "CONDORESEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ALUMNO> ALUMNO
        {
            get
            {
                if ((_ALUMNO == null))
                {
                    _ALUMNO = base.CreateObjectSet<ALUMNO>("ALUMNO");
                }
                return _ALUMNO;
            }
        }
        private ObjectSet<ALUMNO> _ALUMNO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PROFESOR> PROFESOR
        {
            get
            {
                if ((_PROFESOR == null))
                {
                    _PROFESOR = base.CreateObjectSet<PROFESOR>("PROFESOR");
                }
                return _PROFESOR;
            }
        }
        private ObjectSet<PROFESOR> _PROFESOR;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<USUARIO> USUARIO
        {
            get
            {
                if ((_USUARIO == null))
                {
                    _USUARIO = base.CreateObjectSet<USUARIO>("USUARIO");
                }
                return _USUARIO;
            }
        }
        private ObjectSet<USUARIO> _USUARIO;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ALUMNO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToALUMNO(ALUMNO aLUMNO)
        {
            base.AddObject("ALUMNO", aLUMNO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PROFESOR. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPROFESOR(PROFESOR pROFESOR)
        {
            base.AddObject("PROFESOR", pROFESOR);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUSUARIO(USUARIO uSUARIO)
        {
            base.AddObject("USUARIO", uSUARIO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CONDORESModel", Name="ALUMNO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ALUMNO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ALUMNO.
        /// </summary>
        /// <param name="iDALUMNO">Valor inicial de la propiedad IDALUMNO.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="fECHA_NACIMIENTO">Valor inicial de la propiedad FECHA_NACIMIENTO.</param>
        /// <param name="sEXO">Valor inicial de la propiedad SEXO.</param>
        /// <param name="aPODERADO">Valor inicial de la propiedad APODERADO.</param>
        /// <param name="pROFESOR_IDPROFESOR">Valor inicial de la propiedad PROFESOR_IDPROFESOR.</param>
        public static ALUMNO CreateALUMNO(global::System.Int32 iDALUMNO, global::System.String nOMBRE, global::System.DateTime fECHA_NACIMIENTO, global::System.String sEXO, global::System.String aPODERADO, global::System.Int32 pROFESOR_IDPROFESOR)
        {
            ALUMNO aLUMNO = new ALUMNO();
            aLUMNO.IDALUMNO = iDALUMNO;
            aLUMNO.NOMBRE = nOMBRE;
            aLUMNO.FECHA_NACIMIENTO = fECHA_NACIMIENTO;
            aLUMNO.SEXO = sEXO;
            aLUMNO.APODERADO = aPODERADO;
            aLUMNO.PROFESOR_IDPROFESOR = pROFESOR_IDPROFESOR;
            return aLUMNO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDALUMNO
        {
            get
            {
                return _IDALUMNO;
            }
            set
            {
                if (_IDALUMNO != value)
                {
                    OnIDALUMNOChanging(value);
                    ReportPropertyChanging("IDALUMNO");
                    _IDALUMNO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDALUMNO");
                    OnIDALUMNOChanged();
                }
            }
        }
        private global::System.Int32 _IDALUMNO;
        partial void OnIDALUMNOChanging(global::System.Int32 value);
        partial void OnIDALUMNOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_NACIMIENTO
        {
            get
            {
                return _FECHA_NACIMIENTO;
            }
            set
            {
                OnFECHA_NACIMIENTOChanging(value);
                ReportPropertyChanging("FECHA_NACIMIENTO");
                _FECHA_NACIMIENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_NACIMIENTO");
                OnFECHA_NACIMIENTOChanged();
            }
        }
        private global::System.DateTime _FECHA_NACIMIENTO;
        partial void OnFECHA_NACIMIENTOChanging(global::System.DateTime value);
        partial void OnFECHA_NACIMIENTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SEXO
        {
            get
            {
                return _SEXO;
            }
            set
            {
                OnSEXOChanging(value);
                ReportPropertyChanging("SEXO");
                _SEXO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SEXO");
                OnSEXOChanged();
            }
        }
        private global::System.String _SEXO;
        partial void OnSEXOChanging(global::System.String value);
        partial void OnSEXOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String APODERADO
        {
            get
            {
                return _APODERADO;
            }
            set
            {
                OnAPODERADOChanging(value);
                ReportPropertyChanging("APODERADO");
                _APODERADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("APODERADO");
                OnAPODERADOChanged();
            }
        }
        private global::System.String _APODERADO;
        partial void OnAPODERADOChanging(global::System.String value);
        partial void OnAPODERADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PROFESOR_IDPROFESOR
        {
            get
            {
                return _PROFESOR_IDPROFESOR;
            }
            set
            {
                OnPROFESOR_IDPROFESORChanging(value);
                ReportPropertyChanging("PROFESOR_IDPROFESOR");
                _PROFESOR_IDPROFESOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROFESOR_IDPROFESOR");
                OnPROFESOR_IDPROFESORChanged();
            }
        }
        private global::System.Int32 _PROFESOR_IDPROFESOR;
        partial void OnPROFESOR_IDPROFESORChanging(global::System.Int32 value);
        partial void OnPROFESOR_IDPROFESORChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CONDORESModel", "FK_PROF_ALUM", "PROFESOR")]
        public PROFESOR PROFESOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("CONDORESModel.FK_PROF_ALUM", "PROFESOR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("CONDORESModel.FK_PROF_ALUM", "PROFESOR").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PROFESOR> PROFESORReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESOR>("CONDORESModel.FK_PROF_ALUM", "PROFESOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PROFESOR>("CONDORESModel.FK_PROF_ALUM", "PROFESOR", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CONDORESModel", Name="PROFESOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PROFESOR : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PROFESOR.
        /// </summary>
        /// <param name="iDPROFESOR">Valor inicial de la propiedad IDPROFESOR.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="aSIGNATURA">Valor inicial de la propiedad ASIGNATURA.</param>
        /// <param name="cURSO">Valor inicial de la propiedad CURSO.</param>
        public static PROFESOR CreatePROFESOR(global::System.Int32 iDPROFESOR, global::System.String nOMBRE, global::System.String aSIGNATURA, global::System.String cURSO)
        {
            PROFESOR pROFESOR = new PROFESOR();
            pROFESOR.IDPROFESOR = iDPROFESOR;
            pROFESOR.NOMBRE = nOMBRE;
            pROFESOR.ASIGNATURA = aSIGNATURA;
            pROFESOR.CURSO = cURSO;
            return pROFESOR;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPROFESOR
        {
            get
            {
                return _IDPROFESOR;
            }
            set
            {
                if (_IDPROFESOR != value)
                {
                    OnIDPROFESORChanging(value);
                    ReportPropertyChanging("IDPROFESOR");
                    _IDPROFESOR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPROFESOR");
                    OnIDPROFESORChanged();
                }
            }
        }
        private global::System.Int32 _IDPROFESOR;
        partial void OnIDPROFESORChanging(global::System.Int32 value);
        partial void OnIDPROFESORChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ASIGNATURA
        {
            get
            {
                return _ASIGNATURA;
            }
            set
            {
                OnASIGNATURAChanging(value);
                ReportPropertyChanging("ASIGNATURA");
                _ASIGNATURA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ASIGNATURA");
                OnASIGNATURAChanged();
            }
        }
        private global::System.String _ASIGNATURA;
        partial void OnASIGNATURAChanging(global::System.String value);
        partial void OnASIGNATURAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CURSO
        {
            get
            {
                return _CURSO;
            }
            set
            {
                OnCURSOChanging(value);
                ReportPropertyChanging("CURSO");
                _CURSO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CURSO");
                OnCURSOChanged();
            }
        }
        private global::System.String _CURSO;
        partial void OnCURSOChanging(global::System.String value);
        partial void OnCURSOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CONDORESModel", "FK_PROF_ALUM", "ALUMNO")]
        public EntityCollection<ALUMNO> ALUMNO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ALUMNO>("CONDORESModel.FK_PROF_ALUM", "ALUMNO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ALUMNO>("CONDORESModel.FK_PROF_ALUM", "ALUMNO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CONDORESModel", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto USUARIO.
        /// </summary>
        /// <param name="iDUSUARIO">Valor inicial de la propiedad IDUSUARIO.</param>
        /// <param name="uSUARIO1">Valor inicial de la propiedad USUARIO1.</param>
        /// <param name="pASSWORD">Valor inicial de la propiedad PASSWORD.</param>
        public static USUARIO CreateUSUARIO(global::System.Int32 iDUSUARIO, global::System.String uSUARIO1, global::System.String pASSWORD)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.IDUSUARIO = iDUSUARIO;
            uSUARIO.USUARIO1 = uSUARIO1;
            uSUARIO.PASSWORD = pASSWORD;
            return uSUARIO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUSUARIO
        {
            get
            {
                return _IDUSUARIO;
            }
            set
            {
                if (_IDUSUARIO != value)
                {
                    OnIDUSUARIOChanging(value);
                    ReportPropertyChanging("IDUSUARIO");
                    _IDUSUARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUSUARIO");
                    OnIDUSUARIOChanged();
                }
            }
        }
        private global::System.Int32 _IDUSUARIO;
        partial void OnIDUSUARIOChanging(global::System.Int32 value);
        partial void OnIDUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO1
        {
            get
            {
                return _USUARIO1;
            }
            set
            {
                OnUSUARIO1Changing(value);
                ReportPropertyChanging("USUARIO1");
                _USUARIO1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO1");
                OnUSUARIO1Changed();
            }
        }
        private global::System.String _USUARIO1;
        partial void OnUSUARIO1Changing(global::System.String value);
        partial void OnUSUARIO1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();

        #endregion
    
    }

    #endregion
    
}
